### PR TITLE
Add support for gnome 40

### LINKED ISSUE #25: Gnome 40 ?
Hello,

I am just wondering if you could simply add version 40 as an accepted version of Gnome of your extension and create a new release ?

I changed the metadata.json file on my machine to look like this, and it works flawlessly. 

```json
{
    "name": "Spotify Song Label", 
    "description": "Show the currently playing song on Spotify in the top bar", 
    "uuid": "gnomespotifylabel@mheine.github.com", 
    "shell-version": [
        "3.36.4", 
        "40"
     ] 
}
```
Thanks for your work, I really appreciate your extension.

### PR DESCRIPTION
**Pull request by raujonas**
Would close #25

### CODE REVIEW

**Comment by mheine** [comment]
Code looks good to me. I'll verify that this works on 3.36 (my real-life work takes priority, but I'll get to it at some point :raised_hands: ) - and once it's verified that it also works on GNOME 40 I'll merge it and upload a new version to the GNOME website.

**Comment by timocapa** [comment]
Just wanna chime in that it still works on Gnome 40.4.

image

**Comment by mcmxcdev** [comment]
Hey there, awesome work with this GNOME extension, loving it!

I upgraded to Ubuntu 21.10 yesterday, and it would be great to get this running again ;)

Is there an ETA when this will be merged?

Screenshot from 2021-10-15 08-48-45

**Comment by raujonas** [comment]
Works also for 41, added to metadata.

**Comment by mheine** [comment]
Merged, much appreciated!
@raujonas I've sent you a mail regarding further updates as well :ok_hand:

**Pull request merged**
