### PR TITLE
Ads Muter + Pause/Play/Next/Prev actions 

### PR DESCRIPTION
**Pull request by Narixius**
Hi,
I really enjoyed working with this extension. Thank you for this idea.

Well, when I was working with this extension, I just felt It can be something more than just a Spotify "song label" viewer. So I tried to add some features to it.

### 1.Pause/Play/Next/Prev Actions.
image

With this option, users can skip or replay the songs from the top bar.
Added actions:
```
Clicking on next button -> Next song
Clicking on prev button -> Prev song
Clicking on the song label -> Pause/Play the song.
```
> **NOTE:** This feature is configurable from the settings, and users can hide the buttons.

### 2.Advertise Muter
Listening to the annoying ads among my favourite songs was another problem so I just added a simple ads muter.
> **NOTE:** This feature is also configurable from the extension settings.

I was a little hesitant to open this PR because advertise muter and the song controllers may not be related to the purpose of this project that is showing the song labels, but I just wanted to try my luck and share these features with you the main author of this project. It makes me proud to contribute to this extension and make it grow.

I hope you enjoy it.

### CODE REVIEW

**Comment by raujonas** [comment]
I really like this feature and the fact that it is configurable in the settings :blush: 

The only thing is that the click on the song label to toggle the spotify window is not working anymore. A solution for this could be the introduction of an extra play/pause button between the label and the previous and next button (it could be a pause button if the song is currently playing and a play button if the song is stopped).

**Comment by Narixius** [comment]
Thanks, @raujonas, for following up.
I didn't realize this bug. Thanks for mentioning it.
At first, I wanted to add a play/pause button, but I saw it would take too much space. Also, with many active extensions on the top bar, it could be not very pleasant. 

I think we have 2 approaches here.
1. @raujonas' idea

>  A solution for this could be introducing an extra play/pause button between the label and the previous and next button (it could be a pause button if the song is currently playing and a play button if the song is stopped).

2. If the user makes a single click on the label, the song will be paused or played. And if the user makes a double click on the label, the Spotify window will be toggled. (Only if double click action is supported on the buttons)

Also, I think we can implement both of them (Pay/Pause button + approach number 2). And leave it to the user's choice to active or reactive these features from the settings. 

Please let me know which one you prefer. Or share your idea if it can make it more friendly.

**Comment by raujonas** [comment]
I also had the second point on my mind :blush: But I don't know if double click is supported, right click works for sure as an alternative maybe! 

For me it sounds good to have both. Can the play pause button be disabled separately from the previous next buttons? 

Edit: Maybe it would be nice if the icons are not displayed if spotify is closed or to make it configurable too. Currently there's no output if you disable friendly greeting in the settings: 
grafik

**Comment by Narixius** [comment]
> I don't know if double click is supported, right click works for sure as an alternative maybe!

Good idea. I'll check it.

> Can the play pause button be disabled separately from the previous next buttons?

Exactly, I thought it should be separately configurable from prev/next buttons. So another setting option will be added to the settings to disable/enable the pause/play button.

> Maybe it would be nice if the icons are not displayed if spotify is closed or to make it configurable too. Currently there's no output if you disable friendly greeting in the settings:

Oh, I didn't realize this bug too. I'll fix this one and another mentioned before and commit them asap.

Thanks for following up, now I'm sure to continue working on this extension 😉

**Comment by raujonas** [comment]
Sounds good! Let's see what @mheine thinks about these points first :blush:

**Comment by mheine** [comment]
Hi @Narixius! First of all, I want to say that I'm happy to hear your kinds words, and I really do appreciate the work that you have done!

The features you've implemented are very useful - but they are almost "out-of-scope" for this specific extension, in that it was made to be a label, and _only_ a label.

The good news is that @koolskateguy89 has developed his own fork of this extension, and as far as I know he has implemented these features on his fork - available here: https://github.com/koolskateguy89/gnome-shell-extension-spotify-controller
I kind of feel that it is more appropriate for your changes to be applies to his branch, and I'm sure that he'd be a better candidate to discuss these kind of features!

**Comment by mheine** [comment]
One idea would be (as you sort of mentioned) is to have the mouse be the controller. 
I've written a similar kind of "Spotify Label" for Polybar (https://github.com/polybar/polybar), and in that extension I've made

- Left click is pause/play
- Right click is next
- Middle mouse click is previous

If you feel that this is something you'd like to see in the extension, I'd be happy to help (within my limited time) :slightly_smiling_face:

**Comment by Narixius** [comment]
Thank you @mheine for following up.
Yes, I totally agree. I felt too that these features are out-of-scope of this project as I mentioned.

Again I appreciate your works. Thanks for the mouse clicks idea. I'll continue working on this project and try to contact @koolskateguy89.

Peace.

**Pull request closed without merging**
