### PR TITLE
Add toggle window feature

### PR DESCRIPTION
**Pull request by sanjarcode**
Changes in the commit:

Major - Added a new feature: Clicking the label toggles Spotify window / current window
Minor - removed some typos

I don't think a preference option is required.
Tested on Ubuntu 18.04, works even if window is in another workspace.

### CODE REVIEW

**Comment by mheine** [comment]
Heya! Thanks for your contribution - I like the idea!
However, I do believe a preference is required, since this update will move windows to the foreground/background it might disrupt a users workflow if they misclick on the label - and as such I would like the option to turn it off if the user wants to. Feel free to ask if you want help with adding the appropriate setting - I would probably call it something like "Switch to Spotify window on click" :slightly_smiling_face:

**Comment by sanjarcode** [comment]
Okay, I'll implement preferences and and do a PR.

**Comment by mheine** [comment]
You don't have to create a new PR, you can simply push changes to your `sanjarcode:master`-branch (the one you used to create the PR).

**Comment by sanjarcode** [comment]
Done, I've added preferences. I've updated my master with the changes.

**Comment by sanjarcode** [comment]
I had closed the PR, so had to create a new one.

**Pull request closed without merging**
